# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:

    - uses: maxim-lobanov/setup-xcode@v1
    - name: Setup Xcode version
      with: 
        xcode-version: '15.2'
    
    - uses: actions/checkout@v4
    - name: Run tests
      run: | 
        xcodebuild clean test -project GIL/GIL.xcodeproj -scheme GIL -destination "platform=iOS Simulator,name=iPhone 15"
