# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with: 
        xcode-version: '15.4'

    - name: Show current version of Xcode
      run: xcodebuild -version
    
    - uses: actions/checkout@v4
    
    - name: List schemes
      run: xcodebuild -list -project GIL/GIL.xcodeproj
      
    - name: Run tests
      run: | 
        xcodebuild clean test -project GIL/GIL.xcodeproj -scheme GIL -destination "platform=iOS Simulator,name=iPhone 15"
